services:

  app.post.manager:
    class: App\Entity\Manager\PostManager
    arguments:
      - "@doctrine.orm.entity_manager"


    app.event_listener.bad_word:
      class: App\EventListener\BadWordListener
      autowire: false
      tags:
        - { name: kernel.event_listener, event: okApp.pre_validate, method: preValidate }
        - { name: kernel.event_listener, event: okApp.pre_flush, method: onPreFlush }
        - { name: kernel.event_listener, event: okApp.post_flush, method: onPostFlush }
      arguments: ['@logger']
